main: de.timesnake.extension.proxy.main.ExProxy
version: 1.3.0
name: extension-proxy
author: timesnake
depends: [ basic-proxy ]

commands:
  server:
  lobby:
  hub:
  leave:
  menu:

  msg:
  tell:
  message:
  pm:
  r:
  msgx:
  service:
  mail:
  broadcast:
  warn:

  ping:
  bugfind:
     